sudo: false

language: erlang
otp_release:
  - 22.0
  - 21.3

branches:
  except:
  - /SKIPCI.*/

addons:
  apt:
    packages:
      - libexpat1-dev

install: rebar3 compile
script:
  - make all_checks

cache:
  directories:
    - $HOME/.cache/rebar3
